version: "3"

services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kinetic-registry"
